package com.esprit.espritrestau.controllers;

import com.esprit.espritrestau.entities.Abonnement;
import com.esprit.espritrestau.services.AbonnementService;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;

import java.sql.Date;
import java.sql.SQLException;
import java.util.List;

public class AbonnementController {

    @FXML
    private TableView<Abonnement> tableAbonnements;

    @FXML
    private TableColumn<Abonnement, Integer> colId;

    @FXML
    private TableColumn<Abonnement, String> colDateDebut;

    @FXML
    private TableColumn<Abonnement, String> colDateFin;

    @FXML
    private TableColumn<Abonnement, Double> colSolde;

    @FXML
    private TableColumn<Abonnement, Integer> colIdConsomateur;
    @FXML
    private MenuButton consommateurInput;

    @FXML
    private Button createAbonButton;

    @FXML
    private DatePicker dateDebutInput;

    @FXML
    private DatePicker dateFinInput;

    @FXML
    private TextField soldeInput;


    private final AbonnementService abonnementService = new AbonnementService();

    public AbonnementController() throws SQLException {
    }

    @FXML
    public void initialize() {
        // Associer les colonnes aux attributs de l'objet Abonnement
        colId.setCellValueFactory(new PropertyValueFactory<>("id"));
        colDateDebut.setCellValueFactory(new PropertyValueFactory<>("dateDebut"));
        colDateFin.setCellValueFactory(new PropertyValueFactory<>("dateFin"));
        colSolde.setCellValueFactory(new PropertyValueFactory<>("solde"));
        colIdConsomateur.setCellValueFactory(new PropertyValueFactory<>("idConsomateur"));


        tableAbonnements.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);

        loadAbonnements();
    }

    private void loadAbonnements() {
        try {
            List<Abonnement> abonnements = abonnementService.getAllAbonnements();
            ObservableList<Abonnement> observableList = FXCollections.observableArrayList(abonnements);
            tableAbonnements.setItems(observableList);
            System.out.println(abonnements.stream().toList());
        } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }

    }

    @FXML
    void addAbonnement(ActionEvent event) {
        try {
            // Extract data from the form
            Date dateDebut = java.sql.Date.valueOf(dateDebutInput.getValue());
            Date dateFin = java.sql.Date.valueOf(dateFinInput.getValue());
            double solde = Double.parseDouble(soldeInput.getText());
            int idConsomateur = 1;

            Abonnement newAbonnement = new Abonnement(0, dateDebut, dateFin, solde, idConsomateur); // ID will be auto-generated by DB

            abonnementService.addAbonnement(newAbonnement);

            loadAbonnements();
        } catch (Exception e) {
            e.printStackTrace();
            showAlert("Error", "An error occurred while adding the abonnement.");
        }
    }

    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }


}